"""Serializable formal-verification IR and optional backends."""

from .defence_models import (
    camel_ir,
    camel_native_property_ir,
    dual_llm_baseline_ir,
    dual_llm_native_property_ir,
    ites_defective_requester_only_ir,
    ites_reference_ir,
    pact_ir,
    pact_native_property_ir,
    progent_ir,
    progent_native_property_ir,
)
from .endorsement import (
    ENDORSEMENT_SCHEMA_VERSION,
    EndorsementResult,
    defective_endorsement_ir,
    run_endorsement_experiment,
    sound_endorsement_ir,
    verify_endorsement,
)
from .interpreter import (
    DifferentialConformanceResult,
    RuntimeTransitionRecord,
    differential_conformance,
    evaluate,
    initial_state,
    successors,
)
from .ir import (
    Assignment,
    Expression,
    ExpressionKind,
    SafetyInvariant,
    Sort,
    StateVariable,
    TransitionRule,
    VerificationIR,
)
from .nuxmv_backend import NuXmvBackend, NuXmvOutcome, NuXmvRunner
from .plan_ir import EffectSummary, PlanAbstraction, abstract_plan, verify_plan
from .provenance_distinction import (
    AuthorityLoss,
    ExposureMeasure,
    ProvenanceOverapproximation,
    enforcement_is_sound,
    measure_authority_loss,
    measure_exposure,
    measure_overapproximation,
)
from .reduction import (
    REDUCTION_SCHEMA_VERSION,
    ReductionComparison,
    ReferenceSafetyResult,
    VerificationReduction,
    WitnessLiftingEvidence,
    compare_cone_of_influence,
    expression_variables,
    reduce_cone_of_influence,
    reference_safety_check,
)
from .refinement import (
    REFINEMENT_SCHEMA_VERSION,
    RefinementResult,
    SoundAbstractionResult,
    check_refinement,
    check_sound_abstraction,
    run_refinement_experiment,
)
from .results import FormalVerdict, FormalVerificationResult
from .robust_disclosure import (
    ROBUST_DISCLOSURE_SCHEMA_VERSION,
    RobustDisclosureResult,
    defective_disclosure_ir,
    robust_disclosure_ir,
    run_robust_disclosure_experiment,
    verify_robust_disclosure,
)
from .self_composition import (
    SELF_COMPOSITION_SCHEMA_VERSION,
    SecretPartition,
    construct_product_ir,
)
from .synthesis import (
    SYNTHESIS_SCHEMA_VERSION,
    ControllerDecision,
    ControllerStrategy,
    FiniteInstance,
    SynthesisResult,
    default_instance,
    evaluate_strategy,
    run_synthesis_experiment,
    synthesise_controller,
)
from .z3_backend import verify_with_z3

__all__ = [
    "Assignment",
    "AuthorityLoss",
    "ControllerDecision",
    "ControllerStrategy",
    "DifferentialConformanceResult",
    "ENDORSEMENT_SCHEMA_VERSION",
    "EndorsementResult",
    "Expression",
    "ExposureMeasure",
    "ExpressionKind",
    "EffectSummary",
    "FiniteInstance",
    "FormalVerdict",
    "FormalVerificationResult",
    "NuXmvBackend",
    "NuXmvOutcome",
    "NuXmvRunner",
    "PlanAbstraction",
    "ProvenanceOverapproximation",
    "REDUCTION_SCHEMA_VERSION",
    "REFINEMENT_SCHEMA_VERSION",
    "ROBUST_DISCLOSURE_SCHEMA_VERSION",
    "ReductionComparison",
    "ReferenceSafetyResult",
    "RefinementResult",
    "RobustDisclosureResult",
    "RuntimeTransitionRecord",
    "SELF_COMPOSITION_SCHEMA_VERSION",
    "SYNTHESIS_SCHEMA_VERSION",
    "SafetyInvariant",
    "SecretPartition",
    "Sort",
    "SoundAbstractionResult",
    "StateVariable",
    "SynthesisResult",
    "TransitionRule",
    "VerificationIR",
    "VerificationReduction",
    "WitnessLiftingEvidence",
    "abstract_plan",
    "camel_ir",
    "camel_native_property_ir",
    "check_refinement",
    "check_sound_abstraction",
    "compare_cone_of_influence",
    "construct_product_ir",
    "default_instance",
    "defective_disclosure_ir",
    "defective_endorsement_ir",
    "differential_conformance",
    "dual_llm_baseline_ir",
    "dual_llm_native_property_ir",
    "enforcement_is_sound",
    "evaluate",
    "evaluate_strategy",
    "expression_variables",
    "initial_state",
    "ites_defective_requester_only_ir",
    "ites_reference_ir",
    "measure_authority_loss",
    "measure_exposure",
    "measure_overapproximation",
    "pact_ir",
    "pact_native_property_ir",
    "progent_ir",
    "progent_native_property_ir",
    "reduce_cone_of_influence",
    "reference_safety_check",
    "run_endorsement_experiment",
    "run_refinement_experiment",
    "run_synthesis_experiment",
    "run_robust_disclosure_experiment",
    "robust_disclosure_ir",
    "sound_endorsement_ir",
    "successors",
    "synthesise_controller",
    "verify_endorsement",
    "verify_robust_disclosure",
    "verify_with_z3",
    "verify_plan",
]
